#!/bin/bash
# ---------------------------
#
#
# The Seedbox From Scratch Script
#   ---> https://github.com/thevisad/
#
## See Readme.md for License ####
#

echo "" | tee -a ~/.profile

echo "alias md='sudo mkdir'                " |  tee -a ~/.profile
echo "alias copy='sudo cp'                 " |  tee -a ~/.profile
echo "alias rd='sudo rmdir'                " |  tee -a ~/.profile
echo "alias del='sudo rm'                  " |  tee -a ~/.profile
echo "alias cls='sudo clear'               " |  tee -a ~/.profile
echo "alias dir='sudo l'                   " |  tee -a ~/.profile
echo "alias cd..='cd ..'                   " |  tee -a ~/.profile
echo "alias move='sudo mv'                 " |  tee -a ~/.profile
echo "export TERM=linux                    " |  tee -a ~/.profile
echo "export HISTFILESIZE=50000            " |  tee -a ~/.profile
echo "alias locate='locate -i'             " |  tee -a ~/.profile

##################### LAST LINE ###########
