#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
	-h|--hostname)
    SYSTEMHOSTNAME="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

SERVERPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 5051 -ep 5151)

USERUID=$(id -u ${USERNAME})
USERGID=$(id -g ${USERNAME})
echo USERUID  = "${USERUID}"
echo USERGID  = "${USERGID}"
echo USERNAME  = "${USERNAME}"
echo SERVERPORT     = "${SERVERPORT}"

if [ ! -d "/home/${USERNAME}/couchpotato" ]; then
  mkdir /home/${USERNAME}/couchpotato
  mkdir /home/${USERNAME}/couchpotato/config
  mkdir /home/${USERNAME}/couchpotato/data
  chown ${USERNAME}:${USERNAME} /home/${USERNAME}/couchpotato/ -R
fi

echo "USERNAME: $USERNAME" > /home/${USERNAME}/private/couchpotato.txt
echo "SERVERPORT: $SERVERPORT" >> /home/${USERNAME}/private/couchpotato.txt

docker run --restart=always -d --name ${USERNAME}_couchpotato -e LOCAL_USER_ID=${USERUID} -h ${SYSTEMHOSTNAME} -v /home/${USERNAME}/couchpotato/config:/config -v /home/${USERNAME}/couchpotato/data:/data -e PGID=${USERGID} -e PUID=${USERUID} -p ${SERVERPORT}:5050 -v /etc/localtime:/etc/localtime:ro docker-couchpotato
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi