#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 


while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
	-v|--version)
    VERSION="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

SERVERPORT=$(/etc/seedbox-from-scratch/sfsgetAvailablePort -sp 3307 -ep 3406)
USERPASSWDGENED=$(/etc/seedbox-from-scratch/sfsGenerateRandomPasswordString)
ROOTPASSWDGENED=$(/etc/seedbox-from-scratch/sfsGenerateRandomPasswordString)
SYSTEMHOSTNAME=`cat /etc/seedbox-from-scratch/hostname.info`


docker pull mysql:${VERSION}

docker create --restart=always -d --name ${USERNAME}_mysql -h ${SYSTEMHOSTNAME} -v /home/${USERNAME}/mysql:/docker-entrypoint-initdb.d/ -p ${SERVERPORT}:3306 -e MYSQL_ROOT_PASSWORD=${ROOTPASSWDGENED} -e MYSQL_USER=${USERNAME} -e MYSQL_PASSWORD=${USERPASSWDGENED} -v /etc/localtime:/etc/localtime:ro mysql:${VERSION}

sleep 5

CHECKIFRUNNING=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${USERNAME} -d mysql | tr -cd '[[:alnum:]]._-' )
if [[ (${CHECKIFRUNNING} == "STOPPED") || (${CHECKIFRUNNING} == "RUNNING") ]]; then
	echo "SERVICE: MYSQL" > /home/${USERNAME}/private/mysql.serviceinfo
	echo "SERVERPORT: $SERVERPORT" >> /home/${USERNAME}/private/mysql.serviceinfo
	echo "ROOTPASSWORD: $ROOTPASSWDGENED" >> /home/${USERNAME}/private/mysql.serviceinfo
	echo "USERNAME: $USERNAME" >> /home/${USERNAME}/private/mysql.serviceinfo
	echo "USERPASSWORD: $USERPASSWDGENED" >> /home/${USERNAME}/private/mysql.serviceinfo
	chown www-data:www-data  /home/${USERNAME}/private/*.serviceinfo

	if [ ! -d "/home/${USERNAME}/mysql" ]; then
	  mkdir /home/${USERNAME}/mysql
	  chown ${USERNAME}:${USERNAME} /home/${USERNAME}/mysql/ -R
	fi

	if [ ! -f /home/${USERNAME}/mysql/my.cnf ]; then
		cp /etc/seedbox-from-scratch/templates/my.cnf.template /home/${USERNAME}/mysql/my.cnf
		chown ${USERNAME}:${USERNAME} /home/${USERNAME}/mysql/ -R
	fi
fi

docker start --name ${USERNAME}_mysql

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi