#!/bin/bash
# Hellish Tech
# No commercial usage without authorization

if [[ $EUID -ne 0 ] || [ $EUID -ne 33 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

SYSTEMHOSTNAME=`cat /etc/seedbox-from-scratch/hostname.info`
WEBSERVERPORT=$(/etc/seedbox-from-scratch/sfsgetAvailablePort -sp 8081 -ep 8181)
WEBSERVERSSLPORT=$(/etc/seedbox-from-scratch/sfsgetAvailablePort -sp 8444 -ep 8544)
HTPASSWDGENED=$(/etc/seedbox-from-scratch/sfsGenerateUserHtpassword -u ${USERNAME})


USERUID=$(id -u ${USERNAME})
USERGID=$(id -g ${USERNAME})

docker run --restart=always -d --name ${USERNAME}_rapidleech -e LOCAL_USER_ID=${USERUID} -h ${SYSTEMHOSTNAME} -v /home/${USERNAME}/downloads/:/downloads -v /home/${USERNAME}/rapidleech/config:/config -e PGID=${USERGID} -e PUID=${USERUID} -p ${WEBSERVERSSLPORT}:443 -v /etc/seedbox-from-scratch/ssl:/etc/ssl/certs -v /etc/localtime:/etc/localtime:ro hnrapidleech-docker

echo ${HTPASSWDGENED} > /tmp/temp.htpasswd
docker cp /tmp/temp.htpasswd ${USERNAME}_rapidleech:/var/www/.htpasswd
rm -rf /tmp/temp.htpasswd

sleep 5

CHECKIFRUNNING=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${USERNAME} -d rapidleech | tr -cd '[[:alnum:]]._-' )
if [[ (${CHECKIFRUNNING} == "STOPPED") || (${CHECKIFRUNNING} == "RUNNING") ]]; then
	if [ ! -d "/home/${USERNAME}/rapidleech" ]; then
	  mkdir /home/${USERNAME}/rapidleech
	  mkdir /home/${USERNAME}/rapidleech/config
	fi

	echo "SERVICE: RAPIDLEECH" > /home/${USERNAME}/private/rapidleech.serviceinfo
	echo "USERNAME: $USERNAME" >> /home/${USERNAME}/private/rapidleech.serviceinfo
	echo "ACCESSURL: https://$SYSTEMHOSTNAME:$WEBSERVERSSLPORT" >> /home/${USERNAME}/private/rapidleech.serviceinfo
	echo "WEBSERVERPORT: $WEBSERVERPORT" >> /home/${USERNAME}/private/rapidleech.serviceinfo
	echo "WEBSERVERSSLPORT: $WEBSERVERSSLPORT" >> /home/${USERNAME}/private/rapidleech.serviceinfo
	chown www-data:www-data  /home/${USERNAME}/private/*.serviceinfo
fi

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi
