#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    -p|--port)
    SERVERPORT="$2"
    shift # past argument
    ;;
	-wp|--webport)
    WEBSERVERPORT="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done
echo USERNAME  = "${USERNAME}"
echo SERVERPORT     = "${SERVERPORT}"
echo WEBSERVERPORT     = "${SERVERPORT}"
mkdir /home/${USERNAME}/deluge
mkdir /home/${USERNAME}/deluge/config
docker run --restart=always -d --name ${USERNAME}_deluge --net=host -h media.hngamers.com  -v /home/${USERNAME}/downloads/manual:/downloads -v /home/${USERNAME}/deluge/config:/config -p ${WEBSERVERPORT}:8112 -p ${SERVERPORT}:58846 -v /etc/localtime:/etc/localtime:ro linuxserver/deluge
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi