#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 


while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

SYSTEMHOSTNAME=`cat /etc/seedbox-from-scratch/hostname.info`
WEBSERVERPORT=$(/etc/seedbox-from-scratch/sfsgetAvailablePort -sp 8889 -ep 8989)
USERUID=$(id -u ${USERNAME})
USERGID=$(id -g ${USERNAME})

docker run --restart=always -d --name ${USERNAME}_sonarr -e LOCAL_USER_ID=${USERUID} -h ${SYSTEMHOSTNAME} -v /home/${USERNAME}/downloads:/downloads -v /home/${USERNAME}/media/TVShows:/tv -v /home/${USERNAME}/sonarr/config:/config -e PGID=${USERGID} -e PUID=${USERUID} -p ${WEBSERVERPORT}:8989 -v /etc/localtime:/etc/localtime:ro linuxserver/sonarr

sleep 5

CHECKIFRUNNING=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${USERNAME} -d sonarr | tr -cd '[[:alnum:]]._-' )
if [[ (${CHECKIFRUNNING} == "STOPPED") || (${CHECKIFRUNNING} == "RUNNING") ]]; then
	if [ ! -d "/home/${USERNAME}/sonarr" ]; then
	  mkdir /home/${USERNAME}/sonarr
	  mkdir /home/${USERNAME}/sonarr/config
	  chown ${USERNAME}:${USERNAME} /home/${USERNAME}/sonarr/ -R
	fi

	echo "SERVICE: sonarr" > /home/${USERNAME}/private/sonarr.serviceinfo
	echo "USERNAME: $USERNAME" >> /home/${USERNAME}/private/sonarr.serviceinfo
	echo "ACCESSURL: http://$SYSTEMHOSTNAME:$WEBSERVERPORT" >> /home/${USERNAME}/private/sonarr.serviceinfo
	echo "WEBSERVERPORT: $WEBSERVERPORT" >> /home/${USERNAME}/private/sonarr.serviceinfo
	chown www-data:www-data  /home/${USERNAME}/private/*.serviceinfo
fi

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi