#!/bin/bash
# Use -gt 1 to consume two arguments per pass in the loop (e.g. each
# argument has a corresponding value to go with it).
# Use -gt 0 to consume one or more arguments per pass in the loop (e.g.
# some arguments don't have a corresponding value to go with it such
# as in the --default example).
# note: if this is set to -gt 0 the /etc/hosts part is not recognized ( may be a bug )
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--user)
    USERNAME="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

WEBSERVERPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 2203 -ep 2302)
SYSTEMHOSTNAME=`cat /etc/seedbox-from-scratch/hostname.info`

echo USERNAME  = "${USERNAME}"
echo WEBSERVERPORT     = "${WEBSERVERPORT}"
USERUID=$(id -u ${USERNAME})
USERGID=$(id -g ${USERNAME})
echo USERUID  = "${USERUID}"
echo USERGID  = "${USERGID}"

echo "SERVICE: UBOOQUITY" > /home/${USERNAME}/private/ubooquity.serviceinfo
echo "USERNAME: $USERNAME" > /home/${USERNAME}/private/ubooquity.serviceinfo
echo "ACCESSURL: http://$SYSTEMHOSTNAME:$WEBSERVERPORT" >> /home/${USERNAME}/private/ubooquity.serviceinfo
echo "WEBSERVERPORT: $WEBSERVERPORT" >> /home/${USERNAME}/private/ubooquity.serviceinfo
chown www-data:www-data  /home/${USERNAME}/private/*.serviceinfo

if [ ! -d "/home/${USERNAME}/ubooquity" ]; then
  mkdir /home/${USERNAME}/ubooquity
  mkdir /home/${USERNAME}/ubooquity/comics
  mkdir /home/${USERNAME}/ubooquity/books
  mkdir /home/${USERNAME}/ubooquity/config
  mkdir /home/${USERNAME}/ubooquity/files 
  chown ${USERNAME}:${USERNAME} /home/${USERNAME}/ubooquity/ -R
fi

docker run --restart=always -d --name=${USERNAME}_ubooquity -e LOCAL_USER_ID=${USERUID} -h ${SYSTEMHOSTNAME} -v /home/${USERNAME}/ubooquity/config:/config -v /home/${USERNAME}/ubooquity/books:/books -v /home/${USERNAME}/ubooquity/comics:/comics -v /home/${USERNAME}/ubooquity/files:/files -e PGID=${USERGID} -e PUID=${USERUID} -p ${WEBSERVERPORT}:2202 ubooquity-docker -webadmin
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi