#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument
    ;;
    -pu|--plexuser)
    PLEXUSERNAME="$2"
    shift # past argument
    ;;
    -pp|--plexpass)
    PLEXPASSWORD="$2"
    shift # past argument
    ;;
	-h|--hostname)
    SYSTEMHOSTNAME="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

PLEXPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 32401 -ep 32500)

echo USERNAME  = "${USERNAME}"
echo PLEXPORT     = "${PLEXPORT}"
echo PLEX USERNAME    = "${PLEXUSERNAME}"

if [ ! -d "/home/${USERNAME}/plex/config" ]; then
  mkdir /home/${USERNAME}/plex
  mkdir /home/${USERNAME}/plex/config
fi

echo "USERNAME: $USERNAME" > /home/${USERNAME}/private/plex.txt
echo "PLEXPORT: $PLEXPORT" >> /home/${USERNAME}/private/plex.txt
echo "PLEXUSERNAME: $PLEXUSERNAME" >> /home/${USERNAME}/private/plex.txt

docker run --restart=always -d --name ${USERNAME}_plex -v /home/${USERNAME}:/home/${USERNAME} -h ${SYSTEMHOSTNAME} -e PLEX_USERNAME=${PLEXUSERNAME} -e PLEX_PASSWORD=${PLEXPASSWORD} -e PLEX_EXTERNALPORT=${PLEXPORT} -v /home/${USERNAME}/plex/config:/config -p ${PLEXPORT}:32400 timhaak/plex
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi