#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 


while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

SYSTEMHOSTNAME=`cat /etc/seedbox-from-scratch/hostname.info`
WEBSERVERPORT=$(/etc/seedbox-from-scratch/sfsgetAvailablePort -sp 7878 -ep 7978)
USERUID=$(id -u ${USERNAME})
USERGID=$(id -g ${USERNAME})

docker pull linuxserver/radarr

docker run --restart=always -d --name ${USERNAME}_radarr -e LOCAL_USER_ID=${USERUID} -h ${SYSTEMHOSTNAME}  -v /home/${USERNAME}/downloads:/downloads -v /home/${USERNAME}/media/Movies:/movies -v /home/${USERNAME}/radarr/config:/config -e PGID=${USERGID} -e PUID=${USERUID} -p ${WEBSERVERPORT}:7878 -v /etc/localtime:/etc/localtime:ro linuxserver/radarr

sleep 5

CHECKIFRUNNING=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${USERNAME} -d radarr | tr -cd '[[:alnum:]]._-' )
if [[ (${CHECKIFRUNNING} == "STOPPED") || (${CHECKIFRUNNING} == "RUNNING") ]]; then
	if [ ! -d "/home/${USERNAME}/radarr" ]; then
	  mkdir /home/${USERNAME}/radarr
	  mkdir /home/${USERNAME}/radarr/config
	  chown ${USERNAME}:${USERNAME} /home/${USERNAME}/radarr/ -R
	fi

	echo "SERVICE: radarr" > /home/${USERNAME}/private/radarr.serviceinfo
	echo "USERNAME: $USERNAME" >> /home/${USERNAME}/private/radarr.serviceinfo
	echo "ACCESSURL: http://$SYSTEMHOSTNAME:$WEBSERVERPORT" >> /home/${USERNAME}/private/radarr.serviceinfo
	echo "WEBSERVERPORT: $WEBSERVERPORT" >> /home/${USERNAME}/private/radarr.serviceinfo
	echo "Please log in and create a username and password, admins are not responsible for user failure to secure the system." >> /home/${USERNAME}/private/radarr.serviceinfo
	chown www-data:www-data  /home/${USERNAME}/private/*.serviceinfo
fi

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi