#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

SYSTEMHOSTNAME=`cat /etc/seedbox-from-scratch/hostname.info`
WEBSERVERPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 8113 -ep 8212)
SERVERDAEMONPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 58847 -ep 58945)
SERVERTORRENTPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 58947 -ep 59046)
USERUID=$(id -u ${USERNAME})
USERGID=$(id -g ${USERNAME})
echo USERUID  = "${USERUID}"
echo USERGID  = "${USERGID}"
echo USERNAME  = "${USERNAME}"
echo SERVERPORT     = "${SERVERPORT}"
echo WEBSERVERPORT     = "${WEBSERVERPORT}"

if [ ! -d "/home/${USERNAME}/deluge" ]; then
  mkdir /home/${USERNAME}/deluge
  mkdir /home/${USERNAME}/deluge/config
  chown ${USERNAME}:${USERNAME} /home/${USERNAME}/deluge/ -R
fi

echo "SERVICE: DELUGE" > /home/${USERNAME}/private/deluge.serviceinfo
echo "USERNAME: $USERNAME" > /home/${USERNAME}/private/deluge.serviceinfo
echo "ACCESSURL: http://$IPADDRESS1/$WEBSERVERPORT" >> /home/${USERNAME}/private/deluge.serviceinfo
echo "WEBSERVERPORT: $WEBSERVERPORT" >> /home/${USERNAME}/private/deluge.serviceinfo
echo "SERVERDAEMONPORT: $SERVERDAEMONPORT" >> /home/${USERNAME}/private/deluge.serviceinfo
echo "SERVERTORRENTPORT: $SERVERTORRENTPORT" >> /home/${USERNAME}/private/deluge.serviceinfo

docker run --restart=always -d --name ${USERNAME}_deluge -e LOCAL_USER_ID=${USERUID} -h ${SYSTEMHOSTNAME} -v /home/${USERNAME}/downloads/manual:/downloads -v /home/${USERNAME}/deluge/config:/config -e PGID=${USERGID} -e PUID=${USERUID} -p ${WEBSERVERPORT}:8112 -p ${SERVERDAEMONPORT}:58846 -p ${SERVERTORRENTPORT}:58946 -v /etc/localtime:/etc/localtime:ro arch-deluge
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi