#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--user)
    USERNAME="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

WEBSERVERPORT=$(/etc/seedbox-from-scratch/sfsgetAvailablePort -sp 2203 -ep 2302)
SYSTEMHOSTNAME=`cat /etc/seedbox-from-scratch/hostname.info`

USERUID=$(id -u ${USERNAME})
USERGID=$(id -g ${USERNAME})

docker pull linuxserver/ubooquity

docker run --restart=always -d --name=${USERNAME}_ubooquity -e LOCAL_USER_ID=${USERUID} -h ${SYSTEMHOSTNAME} -v /home/${USERNAME}/ubooquity/config:/config -v /home/${USERNAME}/media/books:/books -v /home/${USERNAME}/media/comics:/comics -v /home/${USERNAME}/media/files:/files -e PGID=${USERGID} -e PUID=${USERUID} -p ${WEBSERVERPORT}:2202  -p ${WEBSERVERSSLPORT}:2203 linuxserver/ubooquity -webadmin

sleep 5

CHECKIFRUNNING=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${USERNAME} -d ubooquity | tr -cd '[[:alnum:]]._-' )
if [[ (${CHECKIFRUNNING} == "STOPPED") || (${CHECKIFRUNNING} == "RUNNING") ]]; then
	echo "SERVICE: UBOOQUITY" > /home/${USERNAME}/private/ubooquity.serviceinfo
	echo "USERNAME: $USERNAME" >> /home/${USERNAME}/private/ubooquity.serviceinfo
	echo "ACCESSURL: http://$SYSTEMHOSTNAME:$WEBSERVERPORT" >> /home/${USERNAME}/private/ubooquity.serviceinfo
	echo "WEBSERVERPORT: $WEBSERVERPORT" >> /home/${USERNAME}/private/ubooquity.serviceinfo
	chown www-data:www-data  /home/${USERNAME}/private/*.serviceinfo

	if [ ! -d "/home/${USERNAME}/ubooquity" ]; then
	  mkdir /home/${USERNAME}/ubooquity
	  mkdir /home/${USERNAME}/ubooquity/comics
	  mkdir /home/${USERNAME}/ubooquity/books
	  mkdir /home/${USERNAME}/ubooquity/config
	  mkdir /home/${USERNAME}/ubooquity/files 
	  chown ${USERNAME}:${USERNAME} /home/${USERNAME}/ubooquity/ -R
	fi
fi

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi