#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    -p|--port)
    SERVERPORT="$2"
    shift # past argument
    ;;
	-rp|--rootpassword)
    ROOTPASSWORD="$2"
    shift # past argument
    ;;

    *)
            # unknown option
    ;;
esac
shift # past argument or value
done
echo USERNAME  = "${USERNAME}"
echo SERVERPORT     = "${SERVERPORT}"
mkdir /home/${USERNAME}/mysql
docker run --restart=always -d --name ${USERNAME}_mysql --net=host -h media.hngamers.com -v /home/${USERNAME}/mysql:/var/lib/mysql -v /home/${USERNAME}/mysql/my.cnf:/etc/my.cnf -p ${SERVERPORT}:3306 -e MYSQL_ROOT_HOST=172.17.0.1 -e MYSQL_ROOT_PASSWORD=${ROOTPASSWORD} -v /etc/localtime:/etc/localtime:ro mysql/mysql-server
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi