#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 


while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

SYSTEMHOSTNAME=`cat /etc/seedbox-from-scratch/hostname.info`
WEBSERVERPORT=$(/etc/seedbox-from-scratch/sfsgetAvailablePort -sp 22800 -ep 22900)
USERPASSWORD=$(echo "$(cat /etc/seedbox-from-scratch/users/${USERNAME}.info)" | grep "Password: " | head -n1 | awk '{print $2}')

USERUID=$(id -u ${USERNAME})
USERGID=$(id -g ${USERNAME})

docker pull atmoz/sftp

docker run --restart=always -d --name ${USERNAME}_sftp -e LOCAL_USER_ID=${USERUID} -h ${SYSTEMHOSTNAME} -v /home/${USERNAME}/downloads:/home/${USERNAME}/upload:rw  -v /home/${USERNAME}/sftp/config:/config:rw -e PGID=${USERGID} -e PUID=${USERUID} -p ${WEBSERVERPORT}:22 -v /etc/localtime:/etc/localtime:ro atmoz/sftp ${USERNAME}:${USERPASSWORD}:1001

sleep 5

CHECKIFRUNNING=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${USERNAME} -d sftp | tr -cd '[[:alnum:]]._-' )
if [[ (${CHECKIFRUNNING} == "STOPPED") || (${CHECKIFRUNNING} == "RUNNING") ]]; then
	if [ ! -d "/home/${USERNAME}/sftp" ]; then
	  mkdir /home/${USERNAME}/sftp
	  mkdir /home/${USERNAME}/sftp/config
	  chown ${USERNAME}:${USERNAME} /home/${USERNAME}/sftp/ -R
	fi

	echo "SERVICE: sftp" > /home/${USERNAME}/private/sftp.serviceinfo
	echo "USERNAME: $USERNAME" >> /home/${USERNAME}/private/sftp.serviceinfo
	echo "ACCESSURL: http://$SYSTEMHOSTNAME:$WEBSERVERPORT" >> /home/${USERNAME}/private/sftp.serviceinfo
	echo "WEBSERVERPORT: $WEBSERVERPORT" >> /home/${USERNAME}/private/sftp.serviceinfo
	echo "Please log in and create a username and password, admins are not responsible for user failure to secure the system." >> /home/${USERNAME}/private/sftp.serviceinfo
	chown www-data:www-data  /home/${USERNAME}/private/*.serviceinfo
fi

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi
