#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

USERPASSWORD=$(echo "$(cat /etc/seedbox-from-scratch/users/${USERNAME}.info)" | grep "Password: " | head -n1 | awk '{print $2}')
SYSTEMHOSTNAME=`cat /etc/seedbox-from-scratch/hostname.info`
WEBSERVERPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 8081 -ep 8180)
WEBSSLSERVERPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 8444 -ep 8543)
SERVERPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 51414 -ep 51513)
PREPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 5001 -ep 5100)
UDPPORT=$(/opt/seedbox-from-scratch/sfsgetAvailablePort -sp 6882 -ep 6982)
USERUID=$(id -u ${USERNAME})
USERGID=$(id -g ${USERNAME})
echo USERUID  = "${USERUID}"
echo USERGID  = "${USERGID}"
echo USERNAME  = "${USERNAME}"
echo SERVERPORT     = "${SERVERPORT}"
echo WEBSERVERPORT     = "${WEBSERVERPORT}"
echo WEBSSLSERVERPORT     = "${WEBSSLSERVERPORT}"
echo PREPORT     = "${PREPORT}"
echo UDPPORT     = "${UDPPORT}"

if [ ! -d "/home/${USERNAME}/rtorrent/config" ]; then
  mkdir /home/${USERNAME}/rtorrent
  mkdir /home/${USERNAME}/rtorrent/config
  chown ${USERNAME}:${USERNAME} /home/${USERNAME}/rtorrent/ -R
fi

echo "SERVICE: RTORRENT" > /home/${USERNAME}/private/rutorrent.serviceinfo
echo "USERNAME: $USERNAME" >> /home/${USERNAME}/private/rutorrent.serviceinfo
echo "ACCESSURL: http://$SYSTEMHOSTNAME:$WEBSERVERPORT" >> /home/${USERNAME}/private/rutorrent.serviceinfo
echo "ACCESSURL: https://$SYSTEMHOSTNAME:$WEBSSLSERVERPORT" >> /home/${USERNAME}/private/rutorrent.serviceinfo
echo "SERVERPORT: $SERVERPORT" >> /home/${USERNAME}/private/rutorrent.serviceinfo
echo "WEBSERVERPORT: $WEBSERVERPORT" >> /home/${USERNAME}/private/rutorrent.serviceinfo
echo "WEBSSLSERVERPORT: $WEBSSLSERVERPORT" >> /home/${USERNAME}/private/rutorrent.serviceinfo
echo "PREPORT: $PREPORT" >> /home/${USERNAME}/private/rutorrent.serviceinfo
echo "UDPPORT: $UDPPORT" >> /home/${USERNAME}/private/rutorrent.serviceinfo
chown www-data:www-data  /home/${USERNAME}/private/*.serviceinfo

docker run --restart=always -d --name ${USERNAME}_rutorrent -e LOCAL_USER_ID=${USERUID} -h ${SYSTEMHOSTNAME} -v /home/${USERNAME}/downloads/manual:/downloads -v /home/${USERNAME}/rtorrent/config:/config -e PGID=${USERGID} -e PUID=${USERUID} -p ${WEBSERVERPORT}:80 -p ${WEBSSLSERVERPORT}:443 -p ${PREPORT}:5000 -p ${SERVERPORT}:51413 -p ${UDPPORT}:6881 -v /etc/seedbox-from-scratch/ssl:/etc/ssl/certs -v /etc/localtime:/etc/localtime:ro docker-rutorrent

TEMPUSERPASSWORD=$(perl -le 'print crypt(${USERPASSWORD}, "1XZCQ")')
echo ${TEMPUSERPASSWORD} > /tmp/temp.htpasswd
docker cp /tmp/temp.htpasswd ${USERNAME}_rutorrent:/usr/share/webapps/.htpasswd
rm -rf /tmp/temp.htpasswd

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi