#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 

for f in /etc/seedbox-from-scratch/users/*.info; do
	f=${f##*/}
	#
	# install tasks
	#

	if [ -f "/home/${f%.info}/services/SeedBox.restart" ]
	then
		/etc/seedbox-from-scratch/executeServiceRestart -u ${f%.info}
		rm -rf /home/${f%.info}/services/SeedBox.*

	fi
	
	if [ -f "/home/${f%.info}/services/Plex.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/Plex.*
		else
			DECRYPTPASS=`cat /home/${f%.info}/services/Plex.encrypt`
			ENCRYPTEDUSERNAME=`cat /home/${f%.info}/services/Plex.encrypteduser`
			DECRYPTEDUSERNAME=$(/etc/seedbox-from-scratch/sfsDecryptTemporaryEncryptedText -t ${ENCRYPTEDUSERNAME} -p ${DECRYPTPASS})
			rm -rf /home/${f%.info}/services/Plex.*

			/etc/seedbox-from-scratch/createPlexUserInstall -u ${f%.info} -pt ${DECRYPTEDUSERNAME}
		fi 
	fi
	
	if [ -f "/home/${f%.info}/services/Couchpotato.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d couchpotato )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/Couchpotato.*
			
		else
			rm -rf /home/${f%.info}/services/Couchpotato.*

			/etc/seedbox-from-scratch/createCouchpotatoUserInstall -u ${f%.info} 
		fi

	fi
	
	if [ -f "/home/${f%.info}/services/Deluge.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d deluge )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/Deluge.*
			
		else
			rm -rf /home/${f%.info}/services/Deluge.*

			/etc/seedbox-from-scratch/createDelugeUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/LetsEncrypt.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d letsencrypt )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/LetsEncrypt.*
			
		else
			rm -rf /home/${f%.info}/services/LetsEncrypt.*

			/etc/seedbox-from-scratch/createLetsEncryptUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/MySQL.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d mysql )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/MySQL.*
			
		else
			DECRYPTPASS=`cat /home/${f%.info}/services/MySQL.encrypt`
			VERSION=`cat /home/${f%.info}/services/MySQL.install`
			ENCRYPTEDPASSWORD=`cat /home/${f%.info}/services/MySQL.encyptedrootpass`
			DECRYPTEDPASSWORD=$(/etc/seedbox-from-scratch/sfsDecryptTemporaryEncryptedText -t ${ENCRYPTEDPASSWORD} -p ${DECRYPTPASS})
			
			rm -rf /home/${f%.info}/services/MySQL.*

			/etc/seedbox-from-scratch/createMySQLUserInstall -u ${f%.info} -rp ${DECRYPTEDPASSWORD} -v ${VERSION}
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RapidLeech.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rapidleech )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/RapidLeech.*
			
		else
			rm -rf /home/${f%.info}/services/RapidLeech.*

			/etc/seedbox-from-scratch/createRapidLeechUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RTorrent.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rutorrent )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/RTorrent.*
			
		else
			rm -rf /home/${f%.info}/services/RTorrent.*

			/etc/seedbox-from-scratch/createRTorrentUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sabnzbd.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sabnzbd )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/Sabnzbd.*
			
		else
			rm -rf /home/${f%.info}/services/Sabnzbd.*

			/etc/seedbox-from-scratch/createSabnzbdUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickbeard.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickbeard )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/Sickbeard.*
			
		else
			rm -rf /home/${f%.info}/services/Sickbeard.*

			/etc/seedbox-from-scratch/createSickbeardUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickrage.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickrage )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/Sickrage.*
			
		else
			rm -rf /home/${f%.info}/services/Sickrage.*

			/etc/seedbox-from-scratch/createSickrageUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Ubooquity.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d ubooquity )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 

			rm -rf /home/${f%.info}/services/Ubooquity.*
			
		else
			rm -rf /home/${f%.info}/services/Ubooquity.*

			/etc/seedbox-from-scratch/createUbooquityUserInstall -u ${f%.info} 
		fi
	fi

	#
	# delete tasks
	#
	
	if [ -f "/home/${f%.info}/services/Plex.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Plex.*

			/etc/seedbox-from-scratch/deletePlexUserDocker -u ${f%.info} 
		else

			rm -rf /home/${f%.info}/services/Plex.*
		fi 
	fi
	
	if [ -f "/home/${f%.info}/services/Couchpotato.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d couchpotato )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Couchpotato.*

			/etc/seedbox-from-scratch/deleteCouchpotatoUserDocker -u ${f%.info} 
		else

			rm -rf /home/${f%.info}/services/Couchpotato.*
		fi

	fi
	
	if [ -f "/home/${f%.info}/services/Deluge.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d deluge )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Deluge.*

			/etc/seedbox-from-scratch/deleteDelugeUserDocker -u ${f%.info} 
		else

			rm -rf /home/${f%.info}/services/Deluge.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/LetsEncrypt.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d letsencrypt )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/LetsEncrypt.*

			/etc/seedbox-from-scratch/deleteLetsEncryptUserDocker -u ${f%.info} 
			
			
		else

			rm -rf /home/${f%.info}/services/LetsEncrypt.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/MySQL.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d mysql )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/MySQL.*

			/etc/seedbox-from-scratch/deleteMySQLUserDocker -u ${f%.info} 
		
			
		else

			rm -rf /home/${f%.info}/services/MySQL.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RapidLeech.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rapidleech )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/RapidLeech.*

			/etc/seedbox-from-scratch/deleteRapidLeechUserDocker -u ${f%.info} 
		
			
		else

			rm -rf /home/${f%.info}/services/RapidLeech.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RTorrent.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rutorrent )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/RTorrent.*

			/etc/seedbox-from-scratch/deleteRTorrentUserDocker -u ${f%.info} 
		
			
		else

			rm -rf /home/${f%.info}/services/RTorrent.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sabnzbd.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sabnzbd )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Sabnzbd.*

			/etc/seedbox-from-scratch/deleteSabnzbdUserDocker -u ${f%.info} 
		
			
		else

			rm -rf /home/${f%.info}/services/Sabnzbd.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickbeard.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickbeard )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Sickbeard.*

			/etc/seedbox-from-scratch/deleteSickbeardUserDocker -u ${f%.info} 
		
			
		else

			rm -rf /home/${f%.info}/services/Sickbeard.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickrage.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickrage )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Sickrage.*

			/etc/seedbox-from-scratch/deleteSickrageUserDocker -u ${f%.info} 
		
			
		else

			rm -rf /home/${f%.info}/services/Sickrage.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Ubooquity.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d ubooquity )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Ubooquity.*

			/etc/seedbox-from-scratch/deleteUbooquityUserDocker -u ${f%.info}
		
			
		else

			rm -rf /home/${f%.info}/services/Ubooquity.*
		fi
	fi
	
	#
	# start tasks
	#
	
	if [ -f "/home/${f%.info}/services/Plex.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Plex.*

				/etc/seedbox-from-scratch/startPlexUserDocker -u ${f%.info} 
			else

			fi
		else

			rm -rf /home/${f%.info}/services/Plex.*
		fi 
	fi
	
	if [ -f "/home/${f%.info}/services/Couchpotato.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d couchpotato )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 		
				rm -rf /home/${f%.info}/services/Couchpotato.*

				/etc/seedbox-from-scratch/startCouchpotatoUserDocker -u ${f%.info}
			else

			fi
		else

			rm -rf /home/${f%.info}/services/Couchpotato.*
		fi

	fi
	
	if [ -f "/home/${f%.info}/services/Deluge.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d deluge )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Deluge.*

				/etc/seedbox-from-scratch/startDelugeUserDocker -u ${f%.info} 
			else

			fi
		else

			rm -rf /home/${f%.info}/services/Deluge.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/LetsEncrypt.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d letsencrypt )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/LetsEncrypt.*

				/etc/seedbox-from-scratch/startLetsEncryptUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/LetsEncrypt.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/MySQL.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d mysql )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then
			if [ ${TASKCHECK} == "STOPPED" ]; then 
			
				rm -rf /home/${f%.info}/services/MySQL.*

				/etc/seedbox-from-scratch/startMySQLUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/MySQL.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RapidLeech.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rapidleech )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/RapidLeech.*

				/etc/seedbox-from-scratch/startRapidLeechUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/RapidLeech.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RTorrent.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rutorrent )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/RTorrent.*

				/etc/seedbox-from-scratch/startRTorrentUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/RTorrent.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sabnzbd.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sabnzbd )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Sabnzbd.*

				/etc/seedbox-from-scratch/startSabnzbdUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/Sabnzbd.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickbeard.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickbeard )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Sickbeard.*

				/etc/seedbox-from-scratch/startSickbeardUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/Sickbeard.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickrage.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickrage )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Sickrage.*

				/etc/seedbox-from-scratch/startSickrageUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/Sickrage.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Ubooquity.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d ubooquity )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Ubooquity.*

				/etc/seedbox-from-scratch/startUbooquityUserDocker -u ${f%.info}
			else

			fi		
		else

			rm -rf /home/${f%.info}/services/Ubooquity.*
		fi
	fi
	
	#
	# stop tasks 
	#
	
	if [ -f "/home/${f%.info}/services/Plex.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Plex.*

				/etc/seedbox-from-scratch/stopPlexUserDocker -u ${f%.info} 
			else

			fi
		else

			rm -rf /home/${f%.info}/services/Plex.*
		fi 
	fi
	
	if [ -f "/home/${f%.info}/services/Couchpotato.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d couchpotato )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 		
				rm -rf /home/${f%.info}/services/Couchpotato.*

				/etc/seedbox-from-scratch/stopCouchpotatoUserDocker -u ${f%.info}
			else

			fi
		else

			rm -rf /home/${f%.info}/services/Couchpotato.*
		fi

	fi
	
	if [ -f "/home/${f%.info}/services/Deluge.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d deluge )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Deluge.*

				/etc/seedbox-from-scratch/stopDelugeUserDocker -u ${f%.info} 
			else

			fi
		else

			rm -rf /home/${f%.info}/services/Deluge.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/LetsEncrypt.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d letsencrypt )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/LetsEncrypt.*

				/etc/seedbox-from-scratch/stopLetsEncryptUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/LetsEncrypt.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/MySQL.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d mysql )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then
			if [ ${TASKCHECK} == "RUNNING" ]; then 
			
				rm -rf /home/${f%.info}/services/MySQL.*

				/etc/seedbox-from-scratch/stopMySQLUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/MySQL.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RapidLeech.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rapidleech )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/RapidLeech.*

				/etc/seedbox-from-scratch/stopRapidLeechUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/RapidLeech.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RTorrent.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rutorrent )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/RTorrent.*

				/etc/seedbox-from-scratch/stopRTorrentUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/RTorrent.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sabnzbd.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sabnzbd )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Sabnzbd.*

				/etc/seedbox-from-scratch/stopSabnzbdUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/Sabnzbd.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickbeard.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickbeard )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Sickbeard.*

				/etc/seedbox-from-scratch/stopSickbeardUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/Sickbeard.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickrage.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickrage )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Sickrage.*

				/etc/seedbox-from-scratch/stopSickrageUserDocker -u ${f%.info} 
			else

			fi			
		else

			rm -rf /home/${f%.info}/services/Sickrage.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Ubooquity.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d ubooquity )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Ubooquity.*

				/etc/seedbox-from-scratch/stopUbooquityUserDocker -u ${f%.info}
			else

			fi		
		else

			rm -rf /home/${f%.info}/services/Ubooquity.*
		fi
	fi
	
	# Update Dockers
	if [ -f "/home/${f%.info}/services/Plex.update" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )

		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Plex.*
				/etc/seedbox-from-scratch/updatePlexUserDocker -u ${f%.info} 
			else

			fi
		else

			rm -rf /home/${f%.info}/services/Plex.*
		fi 
	fi
done