#!/bin/bash
# Hellish Tech
# No commercial usage without authorization

for f in /etc/seedbox-from-scratch/users/*.info; do
	f=${f##*/}
	#
	# install tasks
	#

	if [ -f "/home/${f%.info}/services/SeedBox.restart" ]
	then
		/etc/seedbox-from-scratch/executeServiceRestart -u ${f%.info}
		rm -rf /home/${f%.info}/services/SeedBox.*
		logger -t seedboxCronTasks "Seedbox Restarted"
	fi
	
	if [ -f "/home/${f%.info}/services/Plex.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "PLEX ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/Plex.*
		else
			DECRYPTPASS=`cat /home/${f%.info}/services/Plex.encrypt`
			ENCRYPTEDUSERNAME=`cat /home/${f%.info}/services/Plex.encrypteduser`
			DECRYPTEDUSERNAME=$(/etc/seedbox-from-scratch/sfsDecryptTemporaryEncryptedText -t ${ENCRYPTEDUSERNAME} -p ${DECRYPTPASS})
			rm -rf /home/${f%.info}/services/Plex.*
			logger -t seedboxCronTasks "PLEX INSTALLED"
			/etc/seedbox-from-scratch/createPlexUserInstall -u ${f%.info} -pt ${DECRYPTEDUSERNAME}
		fi 
	fi
	
	if [ -f "/home/${f%.info}/services/Couchpotato.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d couchpotato )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "COUCHPOTATO ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/Couchpotato.*
			
		else
			rm -rf /home/${f%.info}/services/Couchpotato.*
			logger -t seedboxCronTasks "COUCHPOTATO INSTALLED"
			/etc/seedbox-from-scratch/createCouchpotatoUserInstall -u ${f%.info} 
		fi

	fi
	
	if [ -f "/home/${f%.info}/services/Deluge.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d deluge )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "DELUGE ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/Deluge.*
			
		else
			rm -rf /home/${f%.info}/services/Deluge.*
			logger -t seedboxCronTasks "DELUGE INSTALLED"
			/etc/seedbox-from-scratch/createDelugeUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/LetsEncrypt.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d letsencrypt )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "LETSENCRYPT ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/LetsEncrypt.*
			
		else
			rm -rf /home/${f%.info}/services/LetsEncrypt.*
			logger -t seedboxCronTasks "LETSENCRYPT INSTALLED"
			/etc/seedbox-from-scratch/createLetsEncryptUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/MySQL.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d mysql )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "MYSQL ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/MySQL.*
			
		else
			DECRYPTPASS=`cat /home/${f%.info}/services/MySQL.encrypt`
			VERSION=`cat /home/${f%.info}/services/MySQL.install`
			ENCRYPTEDPASSWORD=`cat /home/${f%.info}/services/MySQL.encyptedrootpass`
			DECRYPTEDPASSWORD=$(/etc/seedbox-from-scratch/sfsDecryptTemporaryEncryptedText -t ${ENCRYPTEDPASSWORD} -p ${DECRYPTPASS})
			
			rm -rf /home/${f%.info}/services/MySQL.*
			logger -t seedboxCronTasks "MYSQL INSTALLED"
			/etc/seedbox-from-scratch/createMySQLUserInstall -u ${f%.info} -rp ${DECRYPTEDPASSWORD} -v ${VERSION}
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RapidLeech.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rapidleech )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "RAPIDLEECH ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/RapidLeech.*
			
		else
			rm -rf /home/${f%.info}/services/RapidLeech.*
			logger -t seedboxCronTasks "RAPIDLEECH INSTALLED"
			/etc/seedbox-from-scratch/createRapidLeechUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RTorrent.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rutorrent )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "RTORRENT ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/RTorrent.*
			
		else
			rm -rf /home/${f%.info}/services/RTorrent.*
			logger -t seedboxCronTasks "RTORRENT INSTALLED"
			/etc/seedbox-from-scratch/createRTorrentUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sabnzbd.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sabnzbd )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "SABNZBD ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/Sabnzbd.*
			
		else
			rm -rf /home/${f%.info}/services/Sabnzbd.*
			logger -t seedboxCronTasks "SABNZBD INSTALLED"
			/etc/seedbox-from-scratch/createSabnzbdUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickbeard.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickbeard )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "SICKBEARD ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/Sickbeard.*
			
		else
			rm -rf /home/${f%.info}/services/Sickbeard.*
			logger -t seedboxCronTasks "SICKBEARD INSTALLED"
			/etc/seedbox-from-scratch/createSickbeardUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickrage.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickrage )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "SICKRAGE ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/Sickrage.*
			
		else
			rm -rf /home/${f%.info}/services/Sickrage.*
			logger -t seedboxCronTasks "SICKRAGE INSTALLED"
			/etc/seedbox-from-scratch/createSickrageUserInstall -u ${f%.info} 
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Ubooquity.install" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d ubooquity )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			logger -t seedboxCronTasks "UBOOQUITY ALREADY INSTALLED"
			rm -rf /home/${f%.info}/services/Ubooquity.*
			
		else
			rm -rf /home/${f%.info}/services/Ubooquity.*
			logger -t seedboxCronTasks "UBOOQUITY INSTALLED"
			/etc/seedbox-from-scratch/createUbooquityUserInstall -u ${f%.info} 
		fi
	fi

	#
	# delete tasks
	#
	
	if [ -f "/home/${f%.info}/services/Plex.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Plex.*
			logger -t seedboxCronTasks "PLEX DELETED"
			/etc/seedbox-from-scratch/deletePlexUserDocker -u ${f%.info} 
		else
			logger -t seedboxCronTasks "PLEX NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Plex.*
		fi 
	fi
	
	if [ -f "/home/${f%.info}/services/Couchpotato.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d couchpotato )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Couchpotato.*
			logger -t seedboxCronTasks "COUCHPOTATO DELETED"
			/etc/seedbox-from-scratch/deleteCouchpotatoUserDocker -u ${f%.info} 
		else
			logger -t seedboxCronTasks "COUCHPOTATO ALREADY DELETED"
			rm -rf /home/${f%.info}/services/Couchpotato.*
		fi

	fi
	
	if [ -f "/home/${f%.info}/services/Deluge.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d deluge )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Deluge.*
			logger -t seedboxCronTasks "DELUGE DELETED"
			/etc/seedbox-from-scratch/deleteDelugeUserDocker -u ${f%.info} 
		else
			logger -t seedboxCronTasks "DELUGE ALREADY DELETED"
			rm -rf /home/${f%.info}/services/Deluge.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/LetsEncrypt.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d letsencrypt )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/LetsEncrypt.*
			logger -t seedboxCronTasks "LETSENCRYPT DELETED"
			/etc/seedbox-from-scratch/deleteLetsEncryptUserDocker -u ${f%.info} 
			
			
		else
			logger -t seedboxCronTasks "LETSENCRYPT ALREADY DELETED"
			rm -rf /home/${f%.info}/services/LetsEncrypt.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/MySQL.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d mysql )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/MySQL.*
			logger -t seedboxCronTasks "MYSQL DELETED"
			/etc/seedbox-from-scratch/deleteMySQLUserDocker -u ${f%.info} 
		
			
		else
			logger -t seedboxCronTasks "MYSQL ALREADY DELETED"
			rm -rf /home/${f%.info}/services/MySQL.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RapidLeech.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rapidleech )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/RapidLeech.*
			logger -t seedboxCronTasks "RAPIDLEECH DELETED"
			/etc/seedbox-from-scratch/deleteRapidLeechUserDocker -u ${f%.info} 
		
			
		else
			logger -t seedboxCronTasks "RAPIDLEECH ALREADY DELETED"
			rm -rf /home/${f%.info}/services/RapidLeech.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RTorrent.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rutorrent )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/RTorrent.*
			logger -t seedboxCronTasks "RTORRENT DELETED"
			/etc/seedbox-from-scratch/deleteRTorrentUserDocker -u ${f%.info} 
		
			
		else
			logger -t seedboxCronTasks "RTORRENT ALREADY DELETED"
			rm -rf /home/${f%.info}/services/RTorrent.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sabnzbd.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sabnzbd )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Sabnzbd.*
			logger -t seedboxCronTasks "SABNZBD DELETED"
			/etc/seedbox-from-scratch/deleteSabnzbdUserDocker -u ${f%.info} 
		
			
		else
			logger -t seedboxCronTasks "SABNZBD ALREADY DELETED"
			rm -rf /home/${f%.info}/services/Sabnzbd.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickbeard.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickbeard )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Sickbeard.*
			logger -t seedboxCronTasks "SICKBEARD DELETED"
			/etc/seedbox-from-scratch/deleteSickbeardUserDocker -u ${f%.info} 
		
			
		else
			logger -t seedboxCronTasks "SICKBEARD ALREADY DELETED"
			rm -rf /home/${f%.info}/services/Sickbeard.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickrage.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickrage )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Sickrage.*
			logger -t seedboxCronTasks "SICKRAGE DELETED"
			/etc/seedbox-from-scratch/deleteSickrageUserDocker -u ${f%.info} 
		
			
		else
			logger -t seedboxCronTasks "SICKRAGE ALREADY DELETED"
			rm -rf /home/${f%.info}/services/Sickrage.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Ubooquity.delete" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d ubooquity )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			rm -rf /home/${f%.info}/services/Ubooquity.*
			logger -t seedboxCronTasks "UBOOQUITY DELETED"
			/etc/seedbox-from-scratch/deleteUbooquityUserDocker -u ${f%.info}
		
			
		else
		 	logger -t seedboxCronTasks "UBOOQUITY ALREADY DELETED"
			rm -rf /home/${f%.info}/services/Ubooquity.*
		fi
	fi
	
	#
	# start tasks
	#
	
	if [ -f "/home/${f%.info}/services/Plex.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Plex.*
				logger -t seedboxCronTasks "PLEX STARTED"
				/etc/seedbox-from-scratch/startPlexUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi
		else
			logger -t seedboxCronTasks "PLEX NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Plex.*
		fi 
	fi
	
	if [ -f "/home/${f%.info}/services/Couchpotato.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d couchpotato )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 		
				rm -rf /home/${f%.info}/services/Couchpotato.*
				logger -t seedboxCronTasks "COUCHPOTATO STARTED"
				/etc/seedbox-from-scratch/startCouchpotatoUserDocker -u ${f%.info}
			else
				logger -t seedboxCronTasks "COUCHPOTATO ALREADY RUNNING"
			fi
		else
			logger -t seedboxCronTasks "COUCHPOTATO NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Couchpotato.*
		fi

	fi
	
	if [ -f "/home/${f%.info}/services/Deluge.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d deluge )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Deluge.*
				logger -t seedboxCronTasks "DELUGE STARTED"
				/etc/seedbox-from-scratch/startDelugeUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi
		else
			logger -t seedboxCronTasks "DELUGE NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Deluge.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/LetsEncrypt.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d letsencrypt )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/LetsEncrypt.*
				logger -t seedboxCronTasks "LETSENCRYPT STARTED"
				/etc/seedbox-from-scratch/startLetsEncryptUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi			
		else
			logger -t seedboxCronTasks "LETSENCRYPT NOT INSTALLED"
			rm -rf /home/${f%.info}/services/LetsEncrypt.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/MySQL.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d mysql )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then
			if [ ${TASKCHECK} == "STOPPED" ]; then 
			
				rm -rf /home/${f%.info}/services/MySQL.*
				logger -t seedboxCronTasks "MYSQL STARTED"
				/etc/seedbox-from-scratch/startMySQLUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi			
		else
			logger -t seedboxCronTasks "MYSQL NOT INSTALLED"
			rm -rf /home/${f%.info}/services/MySQL.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RapidLeech.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rapidleech )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/RapidLeech.*
				logger -t seedboxCronTasks "RAPIDLEECH STARTED"
				/etc/seedbox-from-scratch/startRapidLeechUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi			
		else
			logger -t seedboxCronTasks "RAPIDLEECH NOT INSTALLED"
			rm -rf /home/${f%.info}/services/RapidLeech.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RTorrent.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rutorrent )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/RTorrent.*
				logger -t seedboxCronTasks "RTORRENT STARTED"
				/etc/seedbox-from-scratch/startRTorrentUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi			
		else
			logger -t seedboxCronTasks "RTORRENT NOT INSTALLED"
			rm -rf /home/${f%.info}/services/RTorrent.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sabnzbd.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sabnzbd )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Sabnzbd.*
				logger -t seedboxCronTasks "SABNZBD STARTED"
				/etc/seedbox-from-scratch/startSabnzbdUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi			
		else
			logger -t seedboxCronTasks "SABNZBD NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Sabnzbd.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickbeard.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickbeard )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Sickbeard.*
				logger -t seedboxCronTasks "SICKBEARD STARTED"
				/etc/seedbox-from-scratch/startSickbeardUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi			
		else
			logger -t seedboxCronTasks "SICKBEARD NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Sickbeard.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickrage.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickrage )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Sickrage.*
				logger -t seedboxCronTasks "SICKRAGE STARTED"
				/etc/seedbox-from-scratch/startSickrageUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi			
		else
			logger -t seedboxCronTasks "SICKRAGE NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Sickrage.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Ubooquity.start" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d ubooquity )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "STOPPED" ]; then 
				rm -rf /home/${f%.info}/services/Ubooquity.*
				logger -t seedboxCronTasks "UBOOQUITY STARTED"
				/etc/seedbox-from-scratch/startUbooquityUserDocker -u ${f%.info}
			else
				logger -t seedboxCronTasks "PLEX ALREADY RUNNING"
			fi		
		else
		 	logger -t seedboxCronTasks "UBOOQUITY NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Ubooquity.*
		fi
	fi
	
	#
	# stop tasks 
	#
	
	if [ -f "/home/${f%.info}/services/Plex.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Plex.*
				logger -t seedboxCronTasks "PLEX STOPPED"
				/etc/seedbox-from-scratch/stopPlexUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi
		else
			logger -t seedboxCronTasks "PLEX NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Plex.*
		fi 
	fi
	
	if [ -f "/home/${f%.info}/services/Couchpotato.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d couchpotato )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 		
				rm -rf /home/${f%.info}/services/Couchpotato.*
				logger -t seedboxCronTasks "COUCHPOTATO STOPPED"
				/etc/seedbox-from-scratch/stopCouchpotatoUserDocker -u ${f%.info}
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi
		else
			logger -t seedboxCronTasks "COUCHPOTATO NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Couchpotato.*
		fi

	fi
	
	if [ -f "/home/${f%.info}/services/Deluge.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d deluge )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Deluge.*
				logger -t seedboxCronTasks "DELUGE STOPPED"
				/etc/seedbox-from-scratch/stopDelugeUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi
		else
			logger -t seedboxCronTasks "DELUGE NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Deluge.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/LetsEncrypt.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d letsencrypt )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/LetsEncrypt.*
				logger -t seedboxCronTasks "LETSENCRYPT STOPPED"
				/etc/seedbox-from-scratch/stopLetsEncryptUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi			
		else
			logger -t seedboxCronTasks "LETSENCRYPT NOT INSTALLED"
			rm -rf /home/${f%.info}/services/LetsEncrypt.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/MySQL.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d mysql )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then
			if [ ${TASKCHECK} == "RUNNING" ]; then 
			
				rm -rf /home/${f%.info}/services/MySQL.*
				logger -t seedboxCronTasks "MYSQL STOPPED"
				/etc/seedbox-from-scratch/stopMySQLUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi			
		else
			logger -t seedboxCronTasks "MYSQL NOT INSTALLED"
			rm -rf /home/${f%.info}/services/MySQL.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RapidLeech.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rapidleech )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/RapidLeech.*
				logger -t seedboxCronTasks "RAPIDLEECH STOPPED"
				/etc/seedbox-from-scratch/stopRapidLeechUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi			
		else
			logger -t seedboxCronTasks "RAPIDLEECH NOT INSTALLED"
			rm -rf /home/${f%.info}/services/RapidLeech.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/RTorrent.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d rutorrent )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/RTorrent.*
				logger -t seedboxCronTasks "RTORRENT STOPPED"
				/etc/seedbox-from-scratch/stopRTorrentUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi			
		else
			logger -t seedboxCronTasks "RTORRENT NOT INSTALLED"
			rm -rf /home/${f%.info}/services/RTorrent.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sabnzbd.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sabnzbd )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Sabnzbd.*
				logger -t seedboxCronTasks "SABNZBD STOPPED"
				/etc/seedbox-from-scratch/stopSabnzbdUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi			
		else
			logger -t seedboxCronTasks "SABNZBD NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Sabnzbd.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickbeard.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickbeard )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Sickbeard.*
				logger -t seedboxCronTasks "SICKBEARD STOPPED"
				/etc/seedbox-from-scratch/stopSickbeardUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi			
		else
			logger -t seedboxCronTasks "SICKBEARD NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Sickbeard.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Sickrage.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d sickrage )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Sickrage.*
				logger -t seedboxCronTasks "SICKRAGE STOPPED"
				/etc/seedbox-from-scratch/stopSickrageUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi			
		else
			logger -t seedboxCronTasks "SICKRAGE NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Sickrage.*
		fi
	fi
	
	if [ -f "/home/${f%.info}/services/Ubooquity.stop" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d ubooquity )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Ubooquity.*
				logger -t seedboxCronTasks "UBOOQUITY STOPPED"
				/etc/seedbox-from-scratch/stopUbooquityUserDocker -u ${f%.info}
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi		
		else
		 	logger -t seedboxCronTasks "UBOOQUITY NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Ubooquity.*
		fi
	fi
	
	# Update Dockers
	if [ -f "/home/${f%.info}/services/Plex.update" ]
	then
		TASKCHECK=$(/etc/seedbox-from-scratch/sfsRunningUserDockerInfo -u ${f%.info} -d plex )
		logger -t seedboxCronTasks ${TASKCHECK}
		if [[ (${TASKCHECK} == "STOPPED") || (${TASKCHECK} == "RUNNING") ]]; then 
			if [ ${TASKCHECK} == "RUNNING" ]; then 
				rm -rf /home/${f%.info}/services/Plex.*
				logger -t seedboxCronTasks "PLEX STOPPED"
				/etc/seedbox-from-scratch/updatePlexUserDocker -u ${f%.info} 
			else
				logger -t seedboxCronTasks "PLEX ALREADY STOPPED"
			fi
		else
			logger -t seedboxCronTasks "PLEX NOT INSTALLED"
			rm -rf /home/${f%.info}/services/Plex.*
		fi 
	fi
done