#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 

/opt/seedbox-from-scratch/updateInstalledScripts

for f in /etc/seedbox-from-scratch/users/*.info; do
	f=${f##*/}
		
	#update web pages for users
	\cp /etc/seedbox-from-scratch/webserver/* /home/${f%.info}/private/
	
	#update scripts for power users (to be removed)
	#\cp /opt/seedbox-from-scratch/templates/user.restartSeedbox.template /home/${f%.info}/restartSeedbox
	#chmod +x /home/${f%.info}/restartSeedbox
done