#!/bin/bash
# Hellish Tech
# No commercial usage without authorization

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--user)
    USERNAME="$2"
    shift # past argument
    ;;
	-d|--dockername)
    DOCKERNAME="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done
echo USERNAME  = "${USERNAME}"
sudo docker rm -f ${USERNAME}_${DOCKERNAME}
rm -rf /home/${USERNAME}/private/${DOCKERNAME}.serviceinfo

case ${DOCKERNAME} in
[1-6]*)
  Message="All is quiet."
  ;;
[7-8]*)
  Message="Start thinking about cleaning out some stuff.  There's a partition that is $space % full."
  ;;
9[1-8])
  Message="Better hurry with that new disk...  One partition is $space % full."
  ;;
99)
  Message="I'm drowning here!  There's a partition at $space %!"
  ;;
*)
  Message="I seem to be running with an nonexistent amount of disk space..."
  ;;
esac

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi
