#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

#clean up running screens
kill `screen -ls | grep $USERNAME | grep tached | awk '{print $1}' | cut -d. -f 1` &> /dev/null
sleep 1
kill -9 `screen -ls | grep $USERNAME | grep tached | awk '{print $1}' | cut -d. -f 1` &> /dev/null
sleep 1
kill -9 `ps aux | grep $USERNAME | grep rtorrent | grep -v grep | awk '{print $2}' | cut -d. -f 1` &> /dev/null
sleep 1
kill -9 `ps aux | grep $USERNAME | grep irssi | grep -v grep | awk '{print $2}' | cut -d. -f 1` &> /dev/null

#clean up rtorrent lock files
rm -f /home/${USERNAME}/downloads/.session/rtorrent.lock
rm -f /home/${USERNAME}/.config/deluge/ipc/deluge-gtk.lock &> /dev/null
sleep 1

#start all required screens
runuser -l  ${USERNAME} -c 'screen -wipe > /dev/null 2>&1'
sleep 1
runuser -l  ${USERNAME} -c 'screen -d -m -S rtorrent rtorrent'
sleep 2
runuser -l  ${USERNAME} -c 'screen -d -m -S irssi irssi'
sleep 1
runuser -l  ${USERNAME} -c "screen -S irssi -p 0 -X stuff '/autodl update^M'"
runuser -l  ${USERNAME} -c 'screen -d -m -S tached tached'

