#!/bin/bash
rm -rf /etc/seedbox-from-scratch/dockers/ubooquity-docker 
rm -rf /etc/seedbox-from-scratch/dockers/docker-rutorrent 
rm -rf /etc/seedbox-from-scratch/dockers/arch-deluge 
rm -rf /etc/seedbox-from-scratch/dockers/mysql-docker
rm -rf /etc/seedbox-from-scratch/dockers/docker-letsencrypt 
rm -rf /etc/seedbox-from-scratch/dockers/docker-sabnzbd 
rm -rf /etc/seedbox-from-scratch/dockers/docker-sickbeard 
rm -rf /etc/seedbox-from-scratch/dockers/docker-couchpotato 
rm -rf /etc/seedbox-from-scratch/dockers/docker-sickrage

cd /etc/seedbox-from-scratch/dockers/hnseedbase-docker/
docker build -t hnseedbase-docker .

cd /etc/seedbox-from-scratch/dockers/hnrapidleech-docker/
docker build -t hnrapidleech-docker .

cd /etc/seedbox-from-scratch/dockers/

git clone https://github.com/binhex/arch-deluge.git
git clone https://github.com/cromigon/ubooquity-docker.git
git clone https://github.com/linuxserver/docker-rutorrent.git
git clone https://github.com/mysql/mysql-docker.git
git clone https://github.com/linuxserver/docker-letsencrypt.git
git clone https://github.com/timhaak/docker-sabnzbd.git
git clone https://github.com/timhaak/docker-sickbeard.git
git clone https://github.com/timhaak/docker-couchpotato.git
git clone https://github.com/timhaak/docker-sickrage.git

chmod 666 /etc/seedbox-from-scratch/dockers/ubooquity-docker/Dockerfile /etc/seedbox-from-scratch/dockers/docker-rutorrent/Dockerfile /etc/seedbox-from-scratch/dockers/arch-deluge/Dockerfile /etc/seedbox-from-scratch/dockers/mysql-docker/5.5/Dockerfile /etc/seedbox-from-scratch/dockers/mysql-docker/5.6/Dockerfile /etc/seedbox-from-scratch/dockers/mysql-docker/5.7/Dockerfile /etc/seedbox-from-scratch/dockers/mysql-docker/8.0/Dockerfile /etc/seedbox-from-scratch/dockers/docker-letsencrypt/Dockerfile /etc/seedbox-from-scratch/dockers/docker-sabnzbd/Dockerfile /etc/seedbox-from-scratch/dockers/docker-sickbeard/Dockerfile /etc/seedbox-from-scratch/dockers/docker-couchpotato/Dockerfile /etc/seedbox-from-scratch/dockers/docker-sickrage/Dockerfile
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/docker-letsencrypt/Dockerfile)" > /etc/seedbox-from-scratch/dockers/docker-letsencrypt/Dockerfile
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/mysql-docker/5.5/Dockerfile)" > /etc/seedbox-from-scratch/dockers/mysql-docker/5.5/Dockerfile
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/mysql-docker/5.6/Dockerfile)" > /etc/seedbox-from-scratch/dockers/mysql-docker/5.6/Dockerfile
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/mysql-docker/5.7/Dockerfile)" > /etc/seedbox-from-scratch/dockers/mysql-docker/5.7/Dockerfile
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/mysql-docker/8.0/Dockerfile)" > /etc/seedbox-from-scratch/dockers/mysql-docker/8.0/Dockerfile
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/ubooquity-docker/Dockerfile)" > /etc/seedbox-from-scratch/dockers/ubooquity-docker/Dockerfile
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/docker-rutorrent/Dockerfile)" > /etc/seedbox-from-scratch/dockers/docker-rutorrent/Dockerfile
perl -pi -e "s/EXPOSE 80/EXPOSE 443/g" /etc/seedbox-from-scratch/dockers/docker-rutorrent/Dockerfile
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/docker-sabnzbd/Dockerfile )" > /etc/seedbox-from-scratch/dockers/docker-sabnzbd/Dockerfile 
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/docker-sickbeard/Dockerfile )" > /etc/seedbox-from-scratch/dockers/docker-sickbeard/Dockerfile 
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/docker-couchpotato/Dockerfile )" > /etc/seedbox-from-scratch/dockers/docker-couchpotato/Dockerfile 
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/docker-sickrage/Dockerfile)" > /etc/seedbox-from-scratch/dockers/docker-sickrage/Dockerfile
echo -e "FROM hnseedbase-docker\nCMD [\"/bin/bash\"]\n$(cat /etc/seedbox-from-scratch/dockers/arch-deluge/Dockerfile)" > /etc/seedbox-from-scratch/dockers/arch-deluge/Dockerfile
chmod 644 /etc/seedbox-from-scratch/dockers/ubooquity-docker/Dockerfile /etc/seedbox-from-scratch/dockers/docker-rutorrent/Dockerfile /etc/seedbox-from-scratch/dockers/arch-deluge/Dockerfile /etc/seedbox-from-scratch/dockers/mysql-docker/5.5/Dockerfile /etc/seedbox-from-scratch/dockers/mysql-docker/5.6/Dockerfile /etc/seedbox-from-scratch/dockers/mysql-docker/5.7/Dockerfile /etc/seedbox-from-scratch/dockers/mysql-docker/8.0/Dockerfile /etc/seedbox-from-scratch/dockers/docker-letsencrypt/Dockerfile /etc/seedbox-from-scratch/dockers/docker-sabnzbd/Dockerfile /etc/seedbox-from-scratch/dockers/docker-sickbeard/Dockerfile /etc/seedbox-from-scratch/dockers/docker-couchpotato/Dockerfile /etc/seedbox-from-scratch/dockers/docker-sickrage/Dockerfile

cd /etc/seedbox-from-scratch/dockers/ubooquity-docker
docker build -t ubooquity-docker .

cd /etc/seedbox-from-scratch/dockers/docker-rutorrent/
cp /etc/seedbox-from-scratch/templates/hnrutorrent.nginx.conf.template /etc/seedbox-from-scratch/dockers/docker-rutorrent/root/defaults/nginx.conf
docker build -t docker-rutorrent .

cd /etc/seedbox-from-scratch/dockers/arch-deluge
docker build -t arch-deluge .

cd /etc/seedbox-from-scratch/dockers/mysql-docker/5.5
docker build -t mysql-docker5.5 .

cd /etc/seedbox-from-scratch/dockers/mysql-docker/5.6
docker build -t mysql-docker5.6 .

cd /etc/seedbox-from-scratch/dockers/mysql-docker/5.7
docker build -t mysql-docker5.7 .

cd /etc/seedbox-from-scratch/dockers/mysql-docker/8.0
docker build -t mysql-docker8.0 .

cd /etc/seedbox-from-scratch/dockers/docker-letsencrypt
docker build -t docker-letsencrypt .

cd /etc/seedbox-from-scratch/dockers/docker-sabnzbd
docker build -t docker-sabnzbd .

cd /etc/seedbox-from-scratch/dockers/docker-sickbeard
docker build -t docker-sickbeard .

cd /etc/seedbox-from-scratch/dockers/docker-couchpotato
docker build -t docker-couchpotato .

cd /etc/seedbox-from-scratch/dockers/docker-sickrage
docker build -t docker-sickrage .

