#!/bin/bash


sudo apt-get purge policykit-1
sudo apt-get update
sudo systemctl reboot
sudo apt-get install policykit-1

sudo apt-get -y install tightvncserver
sudo dpkg -i /etc/seedbox-from-scratch/xrdp_0.6.1-1_`uname -m`.deb
sudo apt-get -f -y install
if 15.04


sudo apt-get -y --force-yes install mate-core mate-desktop-environment mate-notification-daemon
sudo apt-get -y install chromium

echo mate-session >~/.xsession 