#!/bin/bash
MAINUSER1=`cat /etc/seedbox-from-scratch/mainuser.info`
echo `whoami` > ~/name
MU1=`cat ~/name`
if [ "$MU1" = "$MAINUSER1" ]; then
  echo "$(lsb_release -rs)" > ~/v
fi
OSV1=$(sed 's/\..*//' ~/v)
if [ "$(cat ~/bin/rdp)" = "RDP" ] || [ "$(cat ~/bin/nm)" = "RDP" ]; then
  echo "###########################################"
  echo ""
  echo "Wrong Command, You should use RDPconfig.sh"
  echo ""
  echo "###########################################"
  rm ~/name
  exit 1
elif [ "$OSV1" = "15" ]; then
  echo "RDP" >~/bin/nm
  echo "###############################################################################"
  echo ""
  echo ""
  echo ""
  echo "This is Ubuntu 15.XX, Due to a bug with policykit; Your server will reboot and "
  echo "then after reboot you have to run installRDP15 from cmdline"
  echo ""
  echo "Remember installRDP15"
  echo ""
  echo "###############################################################################"
  rm ~/name
  sudo apt-get -y purge policykit-1
  sudo apt-get update
  sudo systemctl reboot
else
  sudo apt-get -y install tightvncserver
  sudo dpkg -i /etc/seedbox-from-scratch/xrdp_0.6.1-1_`uname -m`.deb
  sudo apt-get -f -y install
  sudo apt-get -y --force-yes install mate-core mate-desktop-environment mate-notification-daemon
  sudo apt-get -y install chromium
  rm ~/v
  rm ~/name
  sleep 2
  clear
  echo "RDP" > ~/bin/rdp
  sudo RDPconfig.sh
fi


