#!/bin/bash
#
# The Seedbox From Scratch Script
#   ---> https://github.com/thevisad/
#
#
## See Readme.md for License ###
#

cd /etc/seedbox-from-scratch/installs
sudo apt-get --yes purge sabnzbdplus
sudo apt-get --yes install python-cheetah
sudo apt-get --yes install python-pyopenssl
sudo apt-get --yes install python-openssl
sudo tar xvfz SABnzbd-2.0.0-src.tar.gz
sudo rm -r sabnzbd
sudo mv SABnzbd-2.0.0 sabnzbd
