#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 

RTORRENT1=$1

if [ "$RTORRENT1" = "0.9.6" ]; then
  LIBTORRENT1=0.13.6
fi

if [ "$RTORRENT1" = "0.9.2" ]; then
  LIBTORRENT1=0.13.2
fi

if [ "$RTORRENT1" = "0.9.3" ]; then
  LIBTORRENT1=0.13.3
fi

if [ "$RTORRENT1" = "0.9.4" ]; then
  LIBTORRENT1=0.13.4
fi

if [ ! -d /etc/seedbox-from-scratch/source/rtorrent-$RTORRENT1/ ]; then
  sudo tar xvfz /etc/seedbox-from-scratch/installs/rtorrent-$RTORRENT1.tar.gz -C /etc/seedbox-from-scratch/source/
  sudo tar xvfz /etc/seedbox-from-scratch/installs/libtorrent-$LIBTORRENT1.tar.gz -C /etc/seedbox-from-scratch/source/
fi

sudo killall rtorrent
sudo kill -9 `sudo ps aux | grep rtorrent | grep -v grep | awk '{print $2}' | cut -d. -f 1` &> /dev/null

cd /etc/seedbox-from-scratch/source/libtorrent-$LIBTORRENT1
sudo ./autogen.sh
sudo ./configure --prefix=/usr
sudo make -j2
sudo make install

cd /etc/seedbox-from-scratch/source/rtorrent-$RTORRENT1
sudo ./autogen.sh
sudo ./configure --prefix=/usr --with-xmlrpc-c
sudo make -j2
sudo make install
sudo ldconfig



