#!/bin/bash
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
#Sickrage
echo "Installing SiCKRAGETV . . ."
sudo apt-get -y install python-cheetah python 
cd ~
sudo git clone https://github.com/SiCKRAGETV/SickRage.git /opt/SickRage 
sudo wget http://cheapseedboxes.com/sickrage -P /etc/init.d/ 
sudo chmod +x /etc/init.d/sickrage
sudo wget http://cheapseedboxes.com/csickrage -P /etc/default/ 
sudo update-rc.d sickrage defaults
sudo service sickrage start
echo ""
echo "SiCKRAGETV Installed"
echo "Access - http://$IPADDRESS1:8081 and setup username & password"
echo ""
