#!/bin/bash
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
echo "Installing Plex Media Server . . . ."
if [ `getconf LONG_BIT` = "64" ]; then
  wget -c https://downloads.plex.tv/plex-media-server/0.9.12.11.1406-8403350/plexmediaserver_0.9.12.11.1406-8403350_amd64.deb >> $logfile 2>&1
  sudo dpkg -i plexmediaserver_0.9.12.11.1406-8403350_amd64.deb >> $logfile 2>&1
  sudo apt-get install -f >> $logfile 2>&1
  rm plexmediaserver_0.9.12.11.1406-8403350_amd64.deb
else
  wget -c https://downloads.plex.tv/plex-media-server/0.9.12.11.1406-8403350/plexmediaserver_0.9.12.11.1406-8403350_i386.deb >> $logfile 2>&1
  sudo dpkg -i plexmediaserver_0.9.12.11.1406-8403350_i386.deb >> $logfile 2>&1
  sudo apt-get install -f >> $logfile 2>&1
  rm plexmediaserver_0.9.12.11.1406-8403350_i386.deb
fi
echo ""
echo "Plex Media Server is installed"
echo ""
echo "To enable remote access, set up ssh tunnel;"
echo "and access - http://$IPADDRESS1:32400/web"
echo ""
echo ""
