#!/bin/bash
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
#Sickrage
echo "Installing SiCKRAGETV . . ."
sudo apt-get -y install python-cheetah python
sudo git clone https://github.com/SiCKRAGETV/SickRage.git /opt/SickRage
sudo chown $(whoami):$(whoami) -R /opt/SickRage
mkdir /home/$(whoami)/.sickbeard
sudo wget http://cheapseedboxes.com/sickrage -P /etc/init.d/
sudo chmod +x /etc/init.d/sickrage
sudo wget http://cheapseedboxes.com/csickrage -P /etc/default/
sudo perl -pi -e "s/root/$(whoami)/g" /etc/default/csickrage
sudo perl -pi -e "s/DATADIR=/DATADIR=\/home\/$(whoami)/g" /etc/default/csickrage
sudo update-rc.d sickrage defaults
sudo service sickrage start
echo ""
echo "SiCKRAGETV Installed"
echo "Access - http://$IPADDRESS1:8081 and setup username & password"
echo ""
