#!/bin/bash 

## This script to run after install to install latest znc
MAINUSER1=`cat /etc/seedbox-from-scratch/mainuser.info`
 
## Crontab to start ZNC on reboot
if [ `logname` = "$MAINUSER1" ]; then
  cd ~
  wget --no-check-certificate https://raw.githubusercontent.com/dannyti/sboxsetup/master/startznc
  perl -pi -e "s/USERNAME/`logname`/g" startznc
  chmod +x startznc
  bash startznc
  wget http://znc.in/releases/znc-latest.tar.gz
  tar -xzvf znc*.*gz
  cd znc-*
  ./configure --prefix=$HOME/znc
  make
  make install
  rm -r ~/znc-*
  ~/znc/bin/znc --makeconf
  rm /home/`logname`/startznc
else
  echo "Please install ZNC as Main User"
fi
