#!/bin/bash
# Hellish Tech
# No commercial usage without authorization


IPADDRESS1=`ifconfig | sed -n 's/.*inet addr:\([0-9.]\+\)\s.*/\1/p' | grep -v 127 | head -n 1`
read -p "What is your domain name ? (without the http://): " DOMAIN

sudo sed -i 's/$IPADDRESS1/$DOMAIN/g' /etc/apache2/sites-available/000-default.conf

echo "Thats it, login to https://$DOMAIN/ "