#!/bin/bash

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -t|--text)
    TEXTVALUE="$2"
    shift # past argument 
    ;;
	-p|--password)
    PASSWORD="$2"
    shift # past argument 
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

ENCRYPTEDTEXT=$(echo ${TEXTVALUE} | openssl enc -aes-128-cbc -a -salt -pass pass:${PASSWORD})
echo ENCRYPTEDTEXT
