#!/bin/bash
# Hellish Tech
# No commercial usage without authorization

#RANDOMPASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1) # this is ansible blocking
RANDOMPASS=$(tr -d -c "a-zA-Z0-9" < /dev/urandom | head -c 32) # nice random alphanumeric generator
#RANDOMPASS=$(head -c24 < /dev/urandom | base64 -w0) # this adds + and / characters
echo ${RANDOMPASS}