#!/bin/bash

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument 
    ;;
    *)
    # unknown option
    ;;
esac
shift # past argument or value
done

USERPASSWORD=$(echo "$(cat /etc/seedbox-from-scratch/users/${USERNAME}.info)" | grep "Password: " | head -n1 | awk '{print $2}')

USERHASH=${USERNAME}:$(openssl passwd -apr1 "${USERPASSWORD}")

echo $USERHASH