#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--user)
    USERNAME="$2"
    shift # past argument
    ;;
	-d|--docker)
    DOCKER="$2"
    shift # past argument
    ;;
    *)
    # unknown option
    ;;
esac
shift # past argument or value
done

STOPPED=$(docker ps --filter "status=exited" | grep $USERNAME | grep $DOCKER)
RUNNING=$(docker ps | grep $USERNAME | grep $DOCKER)

if [ ${#STOPPED} -ge 5 ]; then
echo "STOPPED"
else 
	if [ ${#RUNNING} -ge 5 ]; then
	echo "RUNNING"
	else
	echo "NOTINSTALLED"
	fi
fi
