#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 

#Kill all processes that might be running from the old services. 
kill `screen -ls | grep tached | awk '{print $1}' | cut -d. -f 1` &> /dev/null
kill -9 `screen -ls | grep tached | awk '{print $1}' | cut -d. -f 1` &> /dev/null
kill `ps aux | grep SABnzbd | grep -v grep | awk '{print $2}' | cut -d. -f 1` &> /dev/null
kill -9 `ps aux | grep SABnzbd | grep -v grep | awk '{print $2}' | cut -d. -f 1` &> /dev/null
kill -9 `ps aux |  grep deluge | grep -v grep | awk '{print $2}' | cut -d. -f 1` &> /dev/null
kill -9 `ps aux |  grep rtorrent | grep -v grep | awk '{print $2}' | cut -d. -f 1` &> /dev/null
kill -9 `ps aux |  grep irssi | grep -v grep | awk '{print $2}' | cut -d. -f 1` &> /dev/null
kill -9 `ps aux |  grep deluge | grep -v grep | awk '{print $2}' | cut -d. -f 1` &> /dev/null

#Uninstall all previous versions  
cd /etc/seedbox-from-scratch/source/xmlrpc-c-1.16.42/
make uninstall
cd ../libtorrent-0.13.2
make uninstall
cd ../rtorrent-0.9.2
make uninstall
cd ../xmlrpc-c-1.31.06
make uninstall
cd ../deluge-1.3.6
make uninstall

rm -rf /etc/seedbox-from-scratch/downgradeRTorrent /etc/seedbox-from-scratch/installruTorrentStreamPlugin /etc/seedbox-from-scratch/installSABnzbd /etc/seedbox-from-scratch/installCurl /etc/seedbox-from-scratch/installDeluge /etc/seedbox-from-scratch/installRapidleech /etc/seedbox-from-scratch/installRTorrent /etc/seedbox-from-scratch/updategitRepository /etc/seedbox-from-scratch/upgradeRTorrent /etc/seedbox-from-scratch/upgradeSeedbox /etc/seedbox-from-scratch/rutorrent.org/ /etc/seedbox-from-scratch/*.template /etc/seedbox-from-scratch/*.tgz /etc/seedbox-from-scratch/*.deb /etc/seedbox-from-scratch/*.zip /etc/seedbox-from-scratch/*.gz /etc/seedbox-from-scratch/versions /etc/seedbox-from-scratch/source deluge.password.py /etc/seedbox-from-scratch/sabnzbd /var/www/rutorrent /var/www/share /var/www/stream

bash /opt/seedbox-from-scratch/updateInstalledScripts

cp /etc/seedbox-from-scratch/templates/etc.apache2.default.template /etc/apache2/sites-available/default.conf
IPADDRESS1=`ifconfig | sed -n 's/.*inet addr:\([0-9.]\+\)\s.*/\1/p' | grep -v 127 | grep -v 172 | head -n 1`
echo "$IPADDRESS1" > /etc/seedbox-from-scratch/hostname.info

NEWUSER1=`cat /etc/seedbox-from-scratch/mainuser.info`
PASSWORD1=`cat /etc/seedbox-from-scratch/users/$NEWUSER1.info | grep 'Password' | grep -v 'IRSSI' | sed -e 's/Password: //'`
bash /etc/seedbox-from-scratch/changeUserPassword $NEWUSER1 $PASSWORD1 private

perl -pi -e "s/<servername>/$IPADDRESS1/g" /etc/apache2/sites-available/default.conf
perl -pi -e "s/<username>/$NEWUSER1/g" /etc/apache2/sites-available/default.conf

apt-get --yes update
apt-get --yes upgrade

apt-get --yes install apache2 apache2-utils apt-utils autoconf build-essential ca-certificates comerr-dev curl cfv quota mktorrent dtach htop irssi libapache2-mod-php libcloog-ppl-dev libcppunit-dev libcurl3 libcurl4-openssl-dev libncurses5-dev libterm-readline-gnu-perl libsigc++-2.0-dev libperl-dev openvpn libssl-dev libtool libxml2-dev ncurses-base ncurses-term ntp openssl patch libc-ares-dev pkg-config php php-cli php-dev php-curl php-geoip php-mcrypt php-gd php-xmlrpc pkg-config python-scgi screen ssl-cert subversion texinfo unzip zlib1g-dev expect joe automake flex bison debhelper binutils-gold ffmpeg libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl libxml-libxslt-perl libxml-libxml-perl libjson-rpc-perl libarchive-zip-perl tcpdump plowshare4 docker.io nscd handbrake-cli

mkdir /var/www/private
a2ensite default.conf
a2dissite 000-default.conf
a2dissite default-ssl.conf
a2enmod rewrite
service apache2  reload
service apache2  restart

echo "www-data ALL=(ALL) NOPASSWD: /usr/sbin/repquota" | tee -a /etc/sudoers > /dev/null
echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsDecryptTemporaryEncryptedText" | tee -a /etc/sudoers > /dev/null
echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsEncryptTemporaryEncryptedText" | tee -a /etc/sudoers > /dev/null
echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsGenerateRandomPasswordString" | tee -a /etc/sudoers > /dev/null
echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsRunningUserDockerInfo" | tee -a /etc/sudoers > /dev/null
echo "www-data ALL=(ALL) NOPASSWD: /usr/bin/docker" | tee -a /etc/sudoers > /dev/null
echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updatePlexUserDocker" | tee -a /etc/sudoers > /dev/null
cp /etc/seedbox-from-scratch/favicon.ico /var/www/

(crontab -l 2>/dev/null; echo "*/1 * * * * /etc/seedbox-from-scratch/cronTasks >/dev/null 2>&1") | crontab - 
(crontab -l 2>/dev/null; echo "* */1 * * * /etc/seedbox-from-scratch/cronUpdates >/dev/null 2>&1") | crontab - 

