#!/bin/bash
#
#
# The Seedbox From Scratch Script
#   ---> https://github.com/thevisad/
#
## See Readme.md for License ###

sudo chmod +x aliases
sudo chmod +x changeUserPassword
sudo chmod +x createOpenSSLCACertificate
sudo chmod +x createOpenSSLServiceCertificate
sudo chmod +x createPlexUserInstall
sudo chmod +x createDelugeUserInstall
sudo chmod +x createSeedboxUser
sudo chmod +x createUbooquityUserInstall
sudo chmod +x deletePexUserDocker
sudo chmod +x deleteSeedboxUser
sudo chmod +x deleteUserUbooquityDocker
sudo chmod +x downgradeRTorrent
sudo chmod +x installDeluge
sudo chmod +x installDiskspacePlugin
sudo chmod +x installOpenVPN
sudo chmod +x installPLEX
sudo chmod +x installRapidleech
sudo chmod +x installRDP
sudo chmod +x installRDP15
sudo chmod +x installRTorrent
sudo chmod +x installruTorrentStreamPlugin
sudo chmod +x installSABnzbd
sudo chmod +x installSICKRAGE
sudo chmod +x installSUBSONIC
sudo chmod +x installUbooquity
sudo chmod +x installUploader
sudo chmod +x installVNC
sudo chmod +x installWebmin
sudo chmod +x installZNC
sudo chmod +x iptodomain
sudo chmod +x ovpni
sudo chmod +x removeWebmin
sudo chmod +x restartDelugeUserDocker
sudo chmod +x restartPlexUserDocker
sudo chmod +x restartUbooquityUserDocker
sudo chmod +x sickrageconf
sudo chmod +x sickrageservice
sudo chmod +x speedTEST
sudo chmod +x startDelugeUserDocker
sudo chmod +x startPlexUserDocker
sudo chmod +x startUbooquityUserDocker
sudo chmod +x stopDelugeUserDocker
sudo chmod +x stopPlexUserDocker
sudo chmod +x stopUbooquityUserDocker
sudo chmod +x updateExecutables
sudo chmod +x updategitRepository
sudo chmod +x updateInstalledScripts
sudo chmod +x updatejkinit
sudo chmod +x upgradeRTorrent
sudo chmod +x upgradeSeedbox

##################### LAST LINE ###########
