#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
exec 1> >(logger -s -t $(basename $0)) 2>&1 

cd /opt/seedbox-from-scratch/
git stash
git pull

rsync -avz --exclude='/.git' /opt/seedbox-from-scratch/ /etc/seedbox-from-scratch/
cp /etc/seedbox-from-scratch/templates/index.html.template /var/www/index.html

for f in /etc/seedbox-from-scratch/users/*.info; do
	f=${f##*/}
	rsync -avz --exclude='/.git' /opt/seedbox-from-scratch/webserver/ /home/${f%.info}/private/
done