#!/bin/bash
# Hellish Tech
# No commercial usage without authorization



sudo cp /etc/jailkit/jk_init.ini.original /etc/jailkit/jk_init.ini
echo "" | sudo tee -a /etc/jailkit/jk_init.ini >> /dev/null
cat /etc/seedbox-from-scratch/templates/etc.jailkit.jk_init.ini.template | sudo tee -a /etc/jailkit/jk_init.ini >> /dev/null

##################### LAST LINE ###########
