#!/bin/bash
# Hellish Tech

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -u|--username)
    USERNAME="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

HOMEBASE1=/home/$USERNAME
HOMEDIR1=$HOMEBASE1
HOMEJAILED1=$HOMEBASE1
JAILDIR1=$HOMEBASE1

sudo cp /etc/seedbox-from-scratch/webserver/* $HOMEJAILED1/private/