#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

exec 1> >(logger -s -t $(basename $0)) 2>&1 

# Add in all required script functions to the sudoers list

COUNT=$(grep -o "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updatePlexUserDocker" "/etc/sudoers"| wc -l)
if [[ $COUNT -gt 1 ]] ; then
	sed -i "/www-data ALL=(ALL) NOPASSWD: \/etc\/seedbox-from-scratch\/updatePlexUserDocker/d" /etc/sudoers
	else
	echo "Nothing to do" > /dev/nul
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsDecryptTemporaryEncryptedText" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsDecryptTemporaryEncryptedText" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsEncryptTemporaryEncryptedText" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsEncryptTemporaryEncryptedText" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsGenerateRandomPasswordString" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsGenerateRandomPasswordString" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsRunningUserDockerInfo" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsRunningUserDockerInfo" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updatePlexUserDocker" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updatePlexUserDocker" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updateSeedboxUser" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updateSeedboxUser" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsInstalledDockerInfo" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsInstalledDockerInfo" | tee -a /etc/sudoers > /dev/null
fi


# Copy all new scripts to the /etc/seedbox-from-scratch folder structure and force update
yes | cp -rf /opt/seedbox-from-scratch /etc/seedbox-from-scratch

# delete all non required files from the install
rm -rf -R /etc/seedbox-from-scratch/nano
rm -rf -R /etc/seedbox-from-scratch/php
rm -rf -R /etc/seedbox-from-scratch/plugins
rm -rf -R /etc/seedbox-from-scratch/rutorrent.org
rm -rf /etc/seedbox-from-scratch/*.template
rm -rf /etc/seedbox-from-scratch/*.zip
rm -rf /etc/seedbox-from-scratch/*.tgz
rm -rf /etc/seedbox-from-scratch/*.gz
rm -rf /etc/seedbox-from-scratch/*.deb
rm -rf /etc/seedbox-from-scratch/action.php.template
rm -rf /etc/seedbox-from-scratch/add2apache2.conf
rm -rf /etc/seedbox-from-scratch/autodl-trackers.zip
rm -rf /etc/seedbox-from-scratch/versions
rm -rf /etc/seedbox-from-scratch/upgradeSeedbox
rm -rf /etc/seedbox-from-scratch/upgradeRTorrent
rm -rf /etc/seedbox-from-scratch/updategitRepository
rm -rf /etc/seedbox-from-scratch/updateExecutables
rm -rf /etc/seedbox-from-scratch/unpack.conf.php
rm -rf /etc/seedbox-from-scratch/sickrageservice
rm -rf /etc/seedbox-from-scratch/sickrageconf
rm -rf /etc/seedbox-from-scratch/RDPconfig.sh
rm -rf /etc/seedbox-from-scratch/installZNC
rm -rf /etc/seedbox-from-scratch/installVNC
rm -rf /etc/seedbox-from-scratch/installUploader
rm -rf /etc/seedbox-from-scratch/installSUBSONIC
rm -rf /etc/seedbox-from-scratch/installSICKRAGE
rm -rf /etc/seedbox-from-scratch/installSABnzbd
rm -rf /etc/seedbox-from-scratch/installruTorrentStreamPlugin
rm -rf /etc/seedbox-from-scratch/installRDP15
rm -rf /etc/seedbox-from-scratch/installRDP
rm -rf /etc/seedbox-from-scratch/installRapidleech
rm -rf /etc/seedbox-from-scratch/installPLEX
rm -rf /etc/seedbox-from-scratch/installDiskspacePlugin
rm -rf /etc/seedbox-from-scratch/installDeluge
rm -rf /etc/seedbox-from-scratch/installCurl
rm -rf /etc/seedbox-from-scratch/downgradeRTorrent
rm -rf /etc/seedbox-from-scratch/aliases

# Add in the crontab items for the proper execution of the server. 

(crontab -l 2>/dev/null; echo "*/1 * * * * /etc/seedbox-from-scratch/cronTasks >/dev/null 2>&1") | crontab - 
(crontab -l 2>/dev/null; echo "* */1 * * * /etc/seedbox-from-scratch/cronUpdates >/dev/null 2>&1") | crontab - 


getString NO  "Install SABnzbd? " INSTALLSABNZBD1 YES
getString NO  "Install Rapidleech? " INSTALLRAPIDLEECH1 YES
getString NO  "Install Deluge? " INSTALLDELUGE1 YES
getString NO  "Wich RTorrent version would you like to install, '0.9.2' or '0.9.3'? " RTORRENT1 0.9.2
apt-get --yes build-dep znc


#Remove Rutorrent 
rm -rf -R /var/www/rutorrent/plugins/
/var/www/stream
