#!/bin/bash
# Hellish Tech
# No commercial usage without authorization
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

exec 1> >(logger -s -t $(basename $0)) 2>&1 

# Add in all required script functions to the sudoers list

COUNT=$(grep -o "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updatePlexUserDocker" "/etc/sudoers"| wc -l)
if [[ $COUNT -gt 1 ]] ; then
	sed -i "/www-data ALL=(ALL) NOPASSWD: \/etc\/seedbox-from-scratch\/updatePlexUserDocker/d" /etc/sudoers
	else
	echo "Nothing to do" > /dev/nul
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsDecryptTemporaryEncryptedText" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsDecryptTemporaryEncryptedText" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsEncryptTemporaryEncryptedText" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsEncryptTemporaryEncryptedText" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsGenerateRandomPasswordString" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsGenerateRandomPasswordString" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsRunningUserDockerInfo" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsRunningUserDockerInfo" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updatePlexUserDocker" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updatePlexUserDocker" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updateSeedboxUser" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/updateSeedboxUser" | tee -a /etc/sudoers > /dev/null
fi

if grep -q "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsInstalledDockerInfo" "/etc/sudoers"; then
  echo "Nothing to do" > /dev/nul
  else
  echo "www-data ALL=(ALL) NOPASSWD: /etc/seedbox-from-scratch/sfsInstalledDockerInfo" | tee -a /etc/sudoers > /dev/null
fi
